### ISSUE TITLE
ApiRootUrlWithoutTrailingSlash specifics not clear

### ISSUE THREAD

**Issue by n8willis** [ikr/annotator-store-lite#3]
So, you'll be happy to know I am beginning to get this running. But I am seeing something going wrong that I think is with nginx matching requests to the location block....

I can get my OPTIONS request returned correctly, but when the client then tries to GET /annotator-store-lite/annotations it triggers a 404 error with "open() "/srv/www/annotator-store-lite/www/annotator-store-lite/annotations" failed (2: No such file or directory)"

Started digging around. My question is: what is ApiRootUrlWithoutTrailingSlash supposed to be, strictly speaking? Like, is it required to be identical to the 'prefix' that we use in the page to point to the server? Because I am -- by necessity -- providing a full URL in the 'prefix' (which means worrying about CORS and so  on, too, of course). Therefore, my ApiRootUrlWithoutTrailingSlash is not identical to 'prefix' in the page JS.

So I am wondering if this is factoring into the rewriting problem.

**Comment by ikr** [comment]
A 404 on the /srv/www/annotator-store-lite/www/annotator-store-lite/annotations is probably happening because the directory is missing from the server file system.

Sorry I don't remember all that details already. A very useful thing to do for you would be to get the Vagrant box running. It's a local virtual Linux machine with all the services, paths, etc configured automatically with the scripts included into this repository. After the Vagrant box is provisioned, you can ssh into it, and inspect the working configuration. Comparing it to your own config should give the answers.

**Comment by n8willis** [comment]
Well I guess setting up and running Vagrant sounds quick once you've already learned it, but this seems more like an nginx directive mismatch. I can verify, for example, that the directories all exist. AIUI, the location /srv/www/annotator-store-lite/www/annotator-store-lite/annotations isn't supposed to be a directory anyhow. Instead, the /annotator-store-lite/ 'location' block is supposed to match that pattern, then rewrite and pass the "annotator-store-lite/annotations" uri to the php script, in the @annotatorstore block. 

That's the part that doesn't seem to be happening: by putting in some break points and looking at the logs, it's not getting to the @annotatorstore block. So that's why I was wondering if the $uri or $request_uri variables were getting mangled somehow or other.....

**Comment by ikr** [comment]
The directory/file should be writable for nginx, as far as I remember.

Regarding Vagrant, you're right, of course. However, I'd still advise spinning it up, as the whole app setup requires no manual steps then. Here's [the getting-started guide.](https://www.vagrantup.com/intro/getting-started/index.html)
